apiVersion: apps/v1
kind: Deployment
metadata:
  name: boards-service
  labels:
    app: boards-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: boards-service
  template:
    metadata:
      labels:
        app: boards-service
    spec:
      imagePullSecrets:
      - name: ecr-registry-secret
      containers:
      - name: boards-service
        image: 818140567777.dkr.ecr.us-east-1.amazonaws.com/harness_boards_microservice:v1
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: boards-service
spec:
  selector:
    app: boards-service
  ports:
  - port: 8080
    targetPort: 8080